os: osx
language: swift
osx_image: xcode9.2
branches:
  only:
  - master

script:
  - set -o pipefail 
  - xcodebuild -project GPassword/GPassword.xcodeproj -scheme GPassword -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty