os: osx
language: swift
osx_image: xcode9.2
xcode_project: GPassword.xcodeproj
xcode_scheme: GPassword
xcode_sdk: iphonesimulator11.2
branches:
  only:
  - master

# script:
#   - xcodebuild -scheme GPassword -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test