os: osx
language: swift
osx_image: xcode9.2
branches:
  only:
  - master

script:
- set -o pipefail && xcodebuild -workspace GPassword/GPassword.xcodeproj -scheme GPassword -sdk iphonesimulator10.3.1 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' ONLY_ACTIVE_ARCH=NO | xcpretty